#!/bin/bash

# example script for downloading latest cmbootstrap version from GitHub

CMBOOTSTRAP_NAME="cmbootstrap"
CMBOOTSTRAP_FILENAME="/usr/local/bin/$CMBOOTSTRAP_NAME"
CMBOOTSTRAP_GIT_PATH="https://github.com/Priocept/cmbootstrap/raw/master/$CMBOOTSTRAP_NAME"

echo "Downloading cmbootstrap from '$CMBOOTSTRAP_GIT_PATH'..."
wget --output-document="$CMBOOTSTRAP_FILENAME.download" "$CMBOOTSTRAP_GIT_PATH"
if [ "$?" -ne 0 ]; then
    echo "Error downloading cmbootstrap."
    exit 1
fi

mv "$CMBOOTSTRAP_FILENAME.download" "$CMBOOTSTRAP_FILENAME"
chmod +x "$CMBOOTSTRAP_FILENAME"
